[[friends]]
name = "Ryan"
handle = "ryanccn"
href = "https://ryanccn.dev"
met_irl = true

[[friends]]
name = "Sophie"
handle = "soopyc"
href = "https://soopy.moe"
met_irl = true

[[friends]]
name = "Seth"
handle = "getchoo"
href = "https://getchoo.com"

[[friends]]
name = "Sefa"
handle = "Scrumplex"
href = "https://scrumplex.net"

[[friends]]
name = "dish"
handle = "pyrox"
href = "http://pyrox.dev"

[[friends]]
name = "Daniel"
handle = "shedaniel"
href = "https://mastodon.social/@shedaniel"
met_irl = true

[[friends]]
name = "uku"
handle = "uku3lig"
href = "https://uku3lig.net"
met_irl = true

[[friends]]
name = "Stella / twinkle"
handle = "twinkle_mouse"
href = "https://sqky.one"

[[friends]]
name = "Dawn"
handle = "ecorous"
href = "https://ecorous.org"

[[friends]]
name = "Liv"
handle = "europa6502"
href = "https://europa.coralcmd.net"
  
[[friends]]
name = "Adelina"
handle = "m_adelina"
href = "https://adelinam17n.github.io"

[[friends]]
name = "Kyle"
handle = "simplykyle"
href = "https://simplykyle.eu.org"

[[friends]]
name = "Noa"
handle = "noa_virellia"
href = "https://requiem.garden"
met_irl = true

[[friends]]
name = "Shanwer"
handle = "Shanwer"
href = "https://blog.shanwer.top"
met_irl = true

[[friends]]
name = "Aleksana"
handle = "Aleksanaa"
href = "https://aleksana.moe"
met_irl = true

[[friends]]
name = "Kagura"
handle = "kagurachu"
href = "https://kagurach.uk"
met_irl = true

[[friends]]
name = "Renna"
handle = "renna"
href = "https://renna.dev"
met_irl = true

[[friends]]
name = "Cryolitia / 神经元"
handle = "Cryolitia"
href = "https://cryolitia.beiyan.us"
met_irl = true

[[friends]]
name = "Hannes"
handle = "hannesgao"
href = "https://github.com/hannesgao"

[[friends]]
name = "Silryn / 澹隐"
handle = "silryn"
href = "https://www.silryn.com"
met_irl = true

[[friends]]
name = "Ganyu / 王小美"
handle = "Wang_Xiaomei"
href = "https://ganyu.rocks"
met_irl = true

[[friends]]
name = "Sizhe Zhao"
handle = "Prince213"
href = "https://prince213.top"
met_irl = true

[[friends]]
name = "WeepingDogel / 狗子"
handle = "weepingdogel"
href = "https://profile.weepingdogel.vip"
met_irl = true

[[friends]]
name = "Uza"
handle = "uzaaft"
href = "https://uzaaft.me"

[[friends]]
name = "Hanna"
handle = "hqnna"
href = "https://hanna.lol"
met_irl = true

[[friends]]
name = "Yue"
handle = "glauconaryue"
href = "https://linktr.ee/glauconaryue"
met_irl = true

[[friends]]
name = "Mercie"
handle = "mercie.dev"
href = "https://bsky.app/profile/did:plc:r3cudusqgf77v5xpnq5v7g3i"

[[friends]]
name = "clover caruso"
handle = "paperclover"
href = "https://paperclover.net"
